# Generated by Django 2.1.2 on 2018-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not set', max_length=30)),
                ('icon', models.ImageField(upload_to='badges')),
                ('lesson_requirement', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='clientprofileinfo',
            name='badges_earned',
            field=models.TextField(blank=True),
        ),
    ]
