# Generated by Django 2.1.2 on 2018-10-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_auto_20181024_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badges',
            new_name='Badge',
        ),
    ]
